// ----- File: app/layout.js -----
import { Geist_Sans as GeistSans, Geist_Mono as GeistMono } from "next/font/google"; // Corrected import alias for Geist Sans
import "./globals.css";




export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
       
      >
        {children}
      </body>
    </html>
  );
}
// ----- End of File: app/layout.js -----